# Generated by Django 4.1.2 on 2022-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_person_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
