# Generated by Django 4.1.2 on 2022-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_person_description_person_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
