# Generated by Django 4.1.2 on 2022-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_alter_person_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos'),
        ),
    ]
