# Generated by Django 4.1.2 on 2022-12-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_alter_person_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_photo',
        ),
    ]
