# Generated by Django 4.1.2 on 2022-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0007_remove_person_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
